# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\tconsensus\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"t\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12$\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x13.consensus.LogEntry\x12\x15\n\rleader_commit\x18\x04 \x01(\x05\"K\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x05\":\n\x14\x43lientCommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x11\n\tcaller_id\x18\x02 \x01(\x05\"W\n\x15\x43lientCommandResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x13\n\x0bleader_hint\x18\x02 \x01(\t\x12\x17\n\x0f\x63ommitted_index\x18\x03 \x01(\x05\x32\xfc\x01\n\x04Raft\x12L\n\x0bRequestVote\x12\x1d.consensus.RequestVoteRequest\x1a\x1e.consensus.RequestVoteResponse\x12R\n\rAppendEntries\x12\x1f.consensus.AppendEntriesRequest\x1a .consensus.AppendEntriesResponse\x12R\n\rClientCommand\x12\x1f.consensus.ClientCommandRequest\x1a .consensus.ClientCommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY']._serialized_start=54
  _globals['_LOGENTRY']._serialized_end=110
  _globals['_REQUESTVOTEREQUEST']._serialized_start=112
  _globals['_REQUESTVOTEREQUEST']._serialized_end=215
  _globals['_REQUESTVOTERESPONSE']._serialized_start=217
  _globals['_REQUESTVOTERESPONSE']._serialized_end=274
  _globals['_APPENDENTRIESREQUEST']._serialized_start=276
  _globals['_APPENDENTRIESREQUEST']._serialized_end=392
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=394
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=469
  _globals['_CLIENTCOMMANDREQUEST']._serialized_start=471
  _globals['_CLIENTCOMMANDREQUEST']._serialized_end=529
  _globals['_CLIENTCOMMANDRESPONSE']._serialized_start=531
  _globals['_CLIENTCOMMANDRESPONSE']._serialized_end=618
  _globals['_RAFT']._serialized_start=621
  _globals['_RAFT']._serialized_end=873
# @@protoc_insertion_point(module_scope)
