# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: two_phase_commit.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16two_phase_commit.proto\x12\tconsensus\x1a\x1bgoogle/protobuf/empty.proto\"n\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x19\n\x11\x63oordinator_phase\x18\x03 \x01(\t\x12\x1b\n\x13\x63oordinator_node_id\x18\x04 \x01(\t\"S\n\tVoteReply\x12\x0e\n\x06\x63ommit\x18\x01 \x01(\x08\x12\x19\n\x11participant_phase\x18\x02 \x01(\t\x12\x1b\n\x13participant_node_id\x18\x03 \x01(\t\"j\n\x08\x44\x65\x63ision\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\x08\x12\x19\n\x11\x63oordinator_phase\x18\x03 \x01(\t\x12\x1b\n\x13\x63oordinator_node_id\x18\x04 \x01(\t2\x86\x01\n\x0eTwoPhaseCommit\x12;\n\x0bRequestVote\x12\x16.consensus.VoteRequest\x1a\x14.consensus.VoteReply\x12\x37\n\x08\x46inalize\x12\x13.consensus.Decision\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_phase_commit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=66
  _globals['_VOTEREQUEST']._serialized_end=176
  _globals['_VOTEREPLY']._serialized_start=178
  _globals['_VOTEREPLY']._serialized_end=261
  _globals['_DECISION']._serialized_start=263
  _globals['_DECISION']._serialized_end=369
  _globals['_TWOPHASECOMMIT']._serialized_start=372
  _globals['_TWOPHASECOMMIT']._serialized_end=506
# @@protoc_insertion_point(module_scope)
